config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'tweets#index'
  resources :users, only: [:index,:edit, :update, :show] do
    member do
       get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :tweets, only: [:index, :create, :destroy] do
    resources :watch_laters, only: [:create]
  end
  resources :watch_laters, only: [:destroy]
  resources :users do
     resources :watch_laters, only: [:index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :following, class_name: "User"
  validates :follower_id, presence: true
  validates :following_id, presence: true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :watch_laters
  has_many :watch_laters_users, through: :watch_laters, source: :tweet
  validates :content, presence: true
  validates :image, presence: true, if: -> { content.blank? }
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tweets
  has_many :watch_laters
  has_many :watch_later_tweets, through: :watch_laters, source: :tweet

  has_many :following_relationships,class_name:  "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :following_relationships

  has_many :follower_relationships,class_name:  "Relationship", foreign_key: "following_id", dependent: :destroy
  has_many :followers, through: :follower_relationships

 # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end
  # ユーザーをフォローする
  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end
  # ユーザーをアンフォローする
  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end

  def watch_later?(tweet)
    watch_laters.find_by(tweet_id: tweet.id)
  end

  def watch_later!(tweet)
    watch_laters.create!(tweet_id: tweet.id)
  end

  def del_watch_later!(tweet)
    watch_laters.find_by(tweet_id: tweet.id).destroy
  end
  mount_uploader :image, ImageUploader

end

app/models/watch_later.rb
class WatchLater < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :nickname, :image])
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    @user = User.find(params[:relationship][:following_id])
    current_user.follow!(@user)
    redirect_to @user
  end

  def destroy
    @user = Relationship.find(params[:id]).following
    current_user.unfollow!(@user)
    redirect_to @user
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!
  def index
    @tweet = Tweet.new
    @tweets = Tweet.all.order("created_at DESC")
    @users = User.where.not(id: current_user.id).order("RAND()").limit(4)
  end

  def create
    @tweet = Tweet.new(create_params)
    if @tweet.save
      redirect_to tweets_path, notice: "メッセージが送信されました"
    else
      flash.now[:alert] = "メッセージが入力されていません"
      render 'index'
    end
  end


  private
    def create_params
      params.require(:tweet).permit(:content, :image).merge(user_id: current_user.id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
    @tweets = Tweet.order("created_at DESC")
    @CurrentUserTweets = current_user.tweets.order("created_at DESC")
    @users = User.where.not(id: current_user.id).order("RAND()").limit(4)
    @watch_laters = current_user.watch_laters.select("tweet_id")
    @watch_laters_tweets = Tweet.where(id: @watch_laters)
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def show
    @user = User.find(params[:id])
    @usertweets = @user.tweets.order("created_at DESC")
    @users = User.where.not(id: current_user.id).order("RAND()").limit(4)
  end

  def following
    @user  = User.find(params[:id])
    @users = @user.followings
    render 'show_follow'
  end

   def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :image)
  end
end

app/controllers/watch_laters_controller.rb
class WatchLatersController < ApplicationController
  def index
    @user = User.all
    @watch_laters = current_user.watch_laters.select("tweet_id")
    @watch_laters_tweets = Tweet.where(id: @watch_laters)
    @users = User.where.not(id: current_user.id).order("RAND()").limit(4)
  end
  def create
    @user_id = current_user.id
    @tweet_id = Tweet.find(params[:tweet_id]).id
    @watch_later = WatchLater.new(tweet_id: @tweet_id, user_id: @user_id)
    if @watch_later.save
         redirect_to root_path
    end
  end

  def destroy
    @watch_later = WatchLater.find(params[:id])
    if @watch_later.destroy
         redirect_to root_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  # def check_page(controller_name, action_name)
  # controller.controller_name == UsersController && controller.action_name == index
  # end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user?(user)
    user == current_user
  end
end

app/helpers/watch_later_helper.rb
module WatchLaterHelper
end

app/views/tweets/_sidebar-left.html.haml
.sidebar-left
  .profile-card
    .profile-card-box
      %a.profile-card-back-img
        = image_tag current_user.image, size: '' if current_user.image.present?
    .profile-content
      %a.profile-card-me-img
        = image_tag current_user.image, size: '50x50' if current_user.image.present?
      .profile-card-user-fields
        .profile-card-username
          = current_user.name
          %i.fa.fa-lock
        .profile-card-idname
          %a.user-edit
            = link_to users_path(current_user) do
              = "@#{current_user.nickname}"
      .ProfileCardStatus
        %ul.ProfileCardStatus-statuslist
          %li.ProfileCardStatus-status
            %span.u-block
              ツイート
            %span.value
              = current_user.tweets.count
          %li.ProfileCardStatus-status
            %span.u-block
              = link_to following_user_path(current_user) do
                フォロー
            %span.value
              = current_user.followings.count
          %li.ProfileCardStatus-status
            %span.u-block
              = link_to followers_user_path(current_user) do
                フォロワー
            %span.value
              = current_user.followers.count
  / .follow-request
  /   .follow-request-module
  /     %a.follow-request-btn{:href => ""} 10件の新しいフォローリクエスト
  / .trends
  /   .trends-inner
  /     .trends-inner-header
  /       東京のトレンド
  /     .trends-inner-list
  /       .trends-name
  /         天気
  /       .trends-count
  /         3,123件のツイート
  /     .trends-inner-list
  /       .trends-name
  /         Vitamin C
  /       .trends-count
  /         3,333件のツイート

app/views/tweets/_sidebar-right.html.haml
.sidebar-right
  .sidebar-right--top
    .sidebar-right--top--recomend
      %h2.recomend-user
        おすすめユーザー
      .sidebar-right--top--list
        - @users.each do |user|
          .user-profile
            .profile-pic
              = image_tag user.image, size: '50x50' if user.image.present?
            .user-info
              .user.user-name
                = link_to user_path(user) do
                  = user.name
              .user.user-nickname
                = "@#{user.nickname}"
  /   .sidebar-right--top--find
  /     知り合いを見つけましょう
  / .sidebar-right--bottom
  /   .sidebar-right--bottom--list
  /     %li.about
  /       twitter
  /     %li.about
  /       twitter
  /     %li.about
  /       twitter
  /     %li.about
  /       twitter
  /   .sidebar-right--bottom--advertisement
  /     Twitter広告

app/views/tweets/_tweet.html.haml
- @tweets.each do |tweet|
  .tweet
    .profile-pic
      = image_tag tweet.user.image, size: '50x50' if tweet.user.image.present?
    .user-info
      .user.user-name
        = link_to user_path(tweet.user_id) do
          = tweet.user.name
      .user.user-nickname
        = "@#{tweet.user.nickname}"
      .user.user-time
        = time_ago_in_words tweet.created_at
    .tweet-text
      = tweet.content
    .tweet-pic
      = image_tag tweet.image, size: '200x200' if tweet.image.present?
    .tweet-footer
      / .tweet-footer__reply
      /   .tweet-footer__reply--button
      /     %i.fa.fa-comment-o
      /   .tweet-footer__reply--count
      /     12
      / .tweet-footer__retweet
      /   .tweet-footer__retweet--button
      /     %i.fa.fa-retweet
      /   .tweet-footer__retweet--count
      /     43
      / .tweet-footer__favorite
      /   .tweet-footer__favorite--button
      /     %i.fa.fa-thumbs-o-up
      /   .tweet-footer__favorite--count
      /     666
      / .tweet-footer__dm
      /   .tweet-footer__dm--button
      /     %i.fa.fa-envelope-o
      /   .tweet-footer__dm--count
      /     888
      .tweet-footer__watch-later
        / .tweet-footer__watch-later--button
        /   %i.fa.fa-plus
        .tweet-footer__watch-later--link
          - if current_user.watch_later?(tweet)
            = render 'watch_laters/already-add', tweet: tweet
          - else
            = render 'watch_laters/create', tweet: tweet

app/views/users/index.html.haml
=render 'user-topbar'
.page-container
  .ProfileCanopy-header-box
    .ProfileCanopy-header-box--inner
      .ProfileCanopy-header
        %a.ProfileBackImage
          = image_tag current_user.image, size: '' if current_user.image.present?
        .AppContainer
          .ProfileCanopy-avatar
            .ProfileAvatar
              %a.ProfileAvatarImage
                = image_tag current_user.image, size: '200x200' if current_user.image.present?
      .ProfileCanopy-navBar
        .navBar-container
          .navBar-container--child
            .navBar-container--child__mini
              .Profile-nav
                %ul.Profile-nav--list
                  %li.Profile-nav--item.Profile-nav--item__tweets
                    .ProfileNav-stat
                      %span.ProfaileNav-label
                        ツイート
                      %span.ProfaileNav-value
                        = current_user.tweets.count
                  %li.Profile-nav--item.Profile-nav--item__following
                    .ProfileNav-stat
                      %span.ProfaileNav-label
                        = link_to following_user_path(current_user) do
                          フォロー
                      %span.ProfaileNav-value
                        = current_user.followings.count
                  %li.Profile-nav--item.Profile-nav--item__followers
                    .ProfileNav-stat
                      %span.ProfaileNav-label
                        = link_to followers_user_path(current_user) do
                          フォロワー
                      %span.ProfaileNav-value
                        = current_user.followers.count
                  %li.Profile-nav--item.Profile-nav--item__favorites
                    .ProfileNav-stat
                      %span.ProfaileNav-label
                        いいね
                      %span.ProfaileNav-value
                        123
                  %li.Profile-nav--item.Profile-nav--item__list
                    .ProfileNav-stat
                      %span.ProfaileNav-label
                        リスト
                      %span.ProfaileNav-value
                        8
                  %li.Profile-nav--item.Profile-nav--item__moments
                    .ProfileNav-stat
                      %span.ProfaileNav-label
                        モーメント
                      %span.ProfaileNav-value
                        9
                  %li.Profile-nav--item.Profile-nav--item__UserEdit
                    .edit-action
                      .edit-button
                        = link_to edit_user_path(current_user) do
                          プロフィール編集
  .AppContainer
    .AppContainerMain
      .AppContainerMain--left
        .LeftContent
          .LeftContentInner
            .LeftContentInner--Profile
              .Profile-name
                = current_user.name
                %i.fa.fa-lock
              .Profile-nickname
                = "@#{current_user.nickname}"
              .Profile-location
                %i.fa.fa-globe
                japan
              .profile-joinDate
                %i.fa.fa-calendar
                2010年7月に登録
            .LeftContentInner--Pic
              .PicHeader
                .PicHeader--title
                  %i.fa.fa-picture-o
                  画像と動画
              - current_user.tweets.each do |tweet|
                .PicBox
                  .PicBox--pic
                    = image_tag tweet.image, size: '50x50' if tweet.image.present?

      .AppContainerMain--right
        .RightContent-tweets
          .TweetsHeader
            .TweetsHeaderSpace
              .TweetsHeader-menu
                .TweetsHeader-menu--tweets
                  ツイート
                .TweetsHeader-menu--tweetsAndreply
                  ツイートと返信
                .TweetsHeader-menu--media
                  メディア
          - @CurrentUserTweets.each do |tweet|
            .tweet
              .profile-pic
                = image_tag current_user.image, size: '50x50' if current_user.image.present?
              .user-info
                .user.user-name
                  = current_user.name
                .user.user-nickname
                  = "@#{current_user.nickname}"
                .user.user-time
                  = time_ago_in_words tweet.created_at
              .tweet-text
                = tweet.content
              .tweet-pic
                = image_tag tweet.image, size: '200x200' if tweet.image.present?
      .sidebar-right
        .sidebar-right--top
          .sidebar-right--top--recomend
            %h2.recomend-user
              おすすめユーザー
            .sidebar-right--top--list
              - @users.each do |user|
                .user-profile
                  .profile-pic
                    = image_tag user.image, size: '50x50' if user.image.present?
                  .user-info
                    .user.user-name
                      = link_to user_path(user) do
                        = user.name
                    .user.user-nickname
                      = "@#{user.nickname}"
        .sidebar-right--top
          .sidebar-right--top--recomend
            %h2.recomend-user
              = link_to user_watch_laters_path(current_user) do
                あとで見る
            .sidebar-right--top--list
              - @watch_laters_tweets.each do |watch_laters_tweet|
                .user-profile
                  .profile-pic
                    = image_tag watch_laters_tweet.image,size: '50x50' if watch_laters_tweet.image.present?
                  .user-info
                    .user.user-name
                      = watch_laters_tweet.content.truncate(10)

app/views/users/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    %br/

app/views/users/show_follow.html.haml
= render 'user-topbar'
.page-container
  .ProfileCanopy-header-box
    .ProfileCanopy-header-box--inner
      .ProfileCanopy-header
        %a.ProfileBackImage
          = image_tag @user.image, size: '50%' if @user.image.present?
        .AppContainer
          .ProfileCanopy-avatar
            .ProfileAvatar
              %a.ProfileAvatarImage
                = image_tag @user.image, size: '200x200' if @user.image.present?
      .ProfileCanopy-navBar
        .navBar-container
          .navBar-container--child
            .navBar-container--child__mini
              .Profile-nav
                %ul.Profile-nav--list
                  %li.Profile-nav--item.Profile-nav--item__tweets
                    .ProfileNav-stat
                      %span.ProfaileNav-label
                        ツイート
                      %span.ProfaileNav-value
                        = @user.tweets.count
                  %li.Profile-nav--item.Profile-nav--item__following
                    .ProfileNav-stat
                      %span.ProfaileNav-label
                        = link_to following_user_path(@user) do
                          フォロー
                      %span.ProfaileNav-value
                        = @user.followings.count
                  %li.Profile-nav--item.Profile-nav--item__followers
                    .ProfileNav-stat
                      %span.ProfaileNav-label
                        = link_to followers_user_path(@user) do
                          フォロワー
                      %span.ProfaileNav-value
                        = @user.followers.count
                  %li.Profile-nav--item.Profile-nav--item__favorites
                    .ProfileNav-stat
                      %span.ProfaileNav-label
                        いいね
                      %span.ProfaileNav-value
                        123
                  %li.Profile-nav--item.Profile-nav--item__list
                    .ProfileNav-stat
                      %span.ProfaileNav-label
                        リスト
                      %span.ProfaileNav-value
                        8
                  %li.Profile-nav--item.Profile-nav--item__moments
                    .ProfileNav-stat
                      %span.ProfaileNav-label
                        モーメント
                      %span.ProfaileNav-value
                        9
                  %li.Profile-nav--item.Profile-nav--item__UserEdit
                    .edit-action
                      .edit-button
                        = link_to edit_user_path(current_user) do
                          プロフィール編集
  .AppContainer
    .AppContainerMain
      .AppContainerMain--left
        .LeftContent
          .LeftContentInner
            .LeftContentInner--Profile
              .Profile-name
                = @user.name
                %i.fa.fa-lock
              .Profile-nickname
                = "@#{@user.nickname}"
              .Profile-location
                %i.fa.fa-globe
                japan
              .profile-joinDate
                %i.fa.fa-calendar
                2010年7月に登録
              = render 'follow_form' if user_signed_in?
            .LeftContentInner--Pic
              .PicHeader
                .PicHeader--title
                  %i.fa.fa-picture-o
                  画像と動画
              - current_user.tweets.each do |tweet|
                .PicBox
                  .PicBox--pic
                    = image_tag tweet.image, size: '50x50' if tweet.image.present?

      .AppContainerMain--right
        .RightContent-tweets
          .TweetsHeader
            .TweetsHeaderSpace
              .TweetsHeader-menu
                .TweetsHeader-menu--tweets
                  フォロー一覧
          - @user.followings.each do |user|
            .followings-followers
              .followings-followers--profile-pic
                = image_tag user.image, size: '200x200' if user.image.present?
              .followings-followers--user-info
                .user.user-name
                  = user.name
                .user.user-nickname
                  = "@#{user.nickname}"
                .user.detail
                  = link_to '詳細', user_path(user)
      .sidebar-right
        .sidebar-right--top
          .sidebar-right--top--recomend
            %h2.recomend-user
              おすすめユーザー
            .sidebar-right--top--list
              - @users.each do |user|
                .user-profile
                  .profile-pic
                    = image_tag user.image, size: '50x50' if user.image.present?
                  .user-info
                    .user.user-name
                      = link_to user_path(user) do
                        = user.name
                    .user.user-nickname
                      = "@#{user.nickname}"

app/views/users/show_follower.html.haml
= render 'user-topbar'
.page-container
  .ProfileCanopy-header-box
    .ProfileCanopy-header-box--inner
      .ProfileCanopy-header
        %a.ProfileBackImage
          = image_tag @user.image, size: '50%' if @user.image.present?
        .AppContainer
          .ProfileCanopy-avatar
            .ProfileAvatar
              %a.ProfileAvatarImage
                = image_tag @user.image, size: '200x200' if @user.image.present?
      .ProfileCanopy-navBar
        .navBar-container
          .navBar-container--child
            .navBar-container--child__mini
              .Profile-nav
                %ul.Profile-nav--list
                  %li.Profile-nav--item.Profile-nav--item__tweets
                    .ProfileNav-stat
                      %span.ProfaileNav-label
                        ツイート
                      %span.ProfaileNav-value
                        = @user.tweets.count
                  %li.Profile-nav--item.Profile-nav--item__following
                    .ProfileNav-stat
                      %span.ProfaileNav-label
                        = link_to following_user_path(@user) do
                          フォロー
                      %span.ProfaileNav-value
                        = @user.followings.count
                  %li.Profile-nav--item.Profile-nav--item__followers
                    .ProfileNav-stat
                      %span.ProfaileNav-label
                        = link_to followers_user_path(@user) do
                          フォロワー
                      %span.ProfaileNav-value
                        = @user.followers.count
                  %li.Profile-nav--item.Profile-nav--item__favorites
                    .ProfileNav-stat
                      %span.ProfaileNav-label
                        いいね
                      %span.ProfaileNav-value
                        123
                  %li.Profile-nav--item.Profile-nav--item__list
                    .ProfileNav-stat
                      %span.ProfaileNav-label
                        リスト
                      %span.ProfaileNav-value
                        8
                  %li.Profile-nav--item.Profile-nav--item__moments
                    .ProfileNav-stat
                      %span.ProfaileNav-label
                        モーメント
                      %span.ProfaileNav-value
                        9
                  %li.Profile-nav--item.Profile-nav--item__UserEdit
                    .edit-action
                      .edit-button
                        = link_to edit_user_path(current_user) do
                          プロフィール編集
  .AppContainer
    .AppContainerMain
      .AppContainerMain--left
        .LeftContent
          .LeftContentInner
            .LeftContentInner--Profile
              .Profile-name
                = @user.name
                %i.fa.fa-lock
              .Profile-nickname
                = "@#{@user.nickname}"
              .Profile-location
                %i.fa.fa-globe
                japan
              .profile-joinDate
                %i.fa.fa-calendar
                2010年7月に登録
              = render 'follow_form' if user_signed_in?
            .LeftContentInner--Pic
              .PicHeader
                .PicHeader--title
                  %i.fa.fa-picture-o
                  画像と動画
              - current_user.tweets.each do |tweet|
                .PicBox
                  .PicBox--pic
                    = image_tag tweet.image, size: '50x50' if tweet.image.present?

      .AppContainerMain--right
        .RightContent-tweets
          .TweetsHeader
            .TweetsHeaderSpace
              .TweetsHeader-menu
                .TweetsHeader-menu--tweets
                  フォロワー一覧
          - @user.followers.each do |user|
            .followings-followers
              .followings-followers--profile-pic
                = image_tag user.image, size: '200x200' if user.image.present?
              .followings-followers--user-info
                .user.user-name
                  = user.name
                .user.user-nickname
                  = "@#{user.nickname}"
                .user.detail
                  = link_to '詳細', user_path(user)
      .sidebar-right
        .sidebar-right--top
          .sidebar-right--top--recomend
            %h2.recomend-user
              おすすめユーザー
            .sidebar-right--top--list
              - @users.each do |user|
                .user-profile
                  .profile-pic
                    = image_tag user.image, size: '50x50' if user.image.present?
                  .user-info
                    .user.user-name
                      = link_to user_path(user) do
                        = user.name
                    .user.user-nickname
                      = "@#{user.nickname}"

app/views/watch_laters/_already-add.html.haml
.btn.btn-small
  追加済み

app/views/watch_laters/_create.html.haml
= link_to "後で見る", tweet_watch_laters_path(tweet), class: "btn btn-small",method: :post

app/views/watch_laters/index.html.haml
=render 'users/user-topbar'
.page-container
  .ProfileCanopy-header-box
    .ProfileCanopy-header-box--inner
      .ProfileCanopy-header
        %a.ProfileBackImage
          = image_tag current_user.image, size: '' if current_user.image.present?
        .AppContainer
          .ProfileCanopy-avatar
            .ProfileAvatar
              %a.ProfileAvatarImage
                = image_tag current_user.image, size: '200x200' if current_user.image.present?
      .ProfileCanopy-navBar
        .navBar-container
          .navBar-container--child
            .navBar-container--child__mini
              .Profile-nav
                %ul.Profile-nav--list
                  %li.Profile-nav--item.Profile-nav--item__tweets
                    .ProfileNav-stat
                      %span.ProfaileNav-label
                        ツイート
                      %span.ProfaileNav-value
                        = current_user.tweets.count
                  %li.Profile-nav--item.Profile-nav--item__following
                    .ProfileNav-stat
                      %span.ProfaileNav-label
                        = link_to following_user_path(current_user) do
                          フォロー
                      %span.ProfaileNav-value
                        = current_user.followings.count
                  %li.Profile-nav--item.Profile-nav--item__followers
                    .ProfileNav-stat
                      %span.ProfaileNav-label
                        = link_to followers_user_path(current_user) do
                          フォロワー
                      %span.ProfaileNav-value
                        = current_user.followers.count
                  %li.Profile-nav--item.Profile-nav--item__favorites
                    .ProfileNav-stat
                      %span.ProfaileNav-label
                        いいね
                      %span.ProfaileNav-value
                        123
                  %li.Profile-nav--item.Profile-nav--item__list
                    .ProfileNav-stat
                      %span.ProfaileNav-label
                        リスト
                      %span.ProfaileNav-value
                        8
                  %li.Profile-nav--item.Profile-nav--item__moments
                    .ProfileNav-stat
                      %span.ProfaileNav-label
                        モーメント
                      %span.ProfaileNav-value
                        9
                  %li.Profile-nav--item.Profile-nav--item__UserEdit
                    .edit-action
                      .edit-button
                        = link_to edit_user_path(current_user) do
                          プロフィール編集
  .AppContainer
    .AppContainerMain
      .AppContainerMain--left
        .LeftContent
          .LeftContentInner
            .LeftContentInner--Profile
              .Profile-name
                = current_user.name
                %i.fa.fa-lock
              .Profile-nickname
                = "@#{current_user.nickname}"
              .Profile-location
                %i.fa.fa-globe
                japan
              .profile-joinDate
                %i.fa.fa-calendar
                2010年7月に登録
            .LeftContentInner--Pic
              .PicHeader
                .PicHeader--title
                  %i.fa.fa-picture-o
                  画像と動画
              - current_user.tweets.each do |tweet|
                .PicBox
                  .PicBox--pic
                    = image_tag tweet.image, size: '50x50' if tweet.image.present?

      .AppContainerMain--right
        .RightContent-tweets
          .TweetsHeader
            .TweetsHeaderSpace
              .TweetsHeader-menu
                .TweetsHeader-menu--tweets
                  あとで見る
          - @watch_laters_tweets.each do |watch_laters_tweet|
            .tweet
              .profile-pic
                = image_tag watch_laters_tweet.image,size: '50x50' if watch_laters_tweet.user.image.present?
              .user-info
                .user.user-name
                  = current_user.name
                .user.user-nickname
                  = "@#{current_user.nickname}"
                .user.user-time
                  = time_ago_in_words watch_laters_tweet.created_at
              .tweet-text
                = watch_laters_tweet.content
              .tweet-pic
                = image_tag watch_laters_tweet.image,size: '50x50' if watch_laters_tweet.image.present?

      .sidebar-right
        .sidebar-right--top
          .sidebar-right--top--recomend
            %h2.recomend-user
              おすすめユーザー
            .sidebar-right--top--list
              - @users.each do |user|
                .user-profile
                  .profile-pic
                    = image_tag user.image, size: '50x50' if user.image.present?
                  .user-info
                    .user.user-name
                      = link_to user_path(user) do
                        = user.name
                    .user.user-nickname
                      = "@#{user.nickname}"